<?php
	header("Content-type:text/html;charset=utf-8");
	$conn=mysql_connect('210.51.166.148','yucheng','yucheng');
	mysql_query('set names utf8');
	mysql_select_db('shop');
	/*$conn=mysql_connect('localhost','root','');
	mysql_query('set names utf8');
	mysql_select_db('shop2');*/
	$date1=date("Y-m-d",time());
	$date2=date("Y-m-d",time()+24*3600);
	$res1=mysql_query("SELECT  b.order_sn, a.goods_name,a.goods_attr, a.goods_number,b.surplus,b.goods_amount,b.bonus,b.money_paid,b.order_amount, b.pay_name,b.pay_note,best_time FROM `ecs_order_goods` AS a LEFT JOIN ecs_order_info AS b ON a.order_id = b.order_id WHERE b.order_status=1 
						AND a.goods_price >=45 and best_time like '%".$date1."%' ORDER BY surplus desc,bonus desc,pay_note desc");
	$order_list1=array();				
	while($row=mysql_fetch_assoc($res1))
	{
		$order_list1[]=$row;
	}
	$ljk=0;
	$normal=0;
	$cuxiao=0;
	$yuejie=0;
	$xshd=0;
	$schd=0;
	$scmini=0;
	$total_cake=0;
	foreach($order_list1 as $val)
	{
		if($val['surplus']>0)
		{
			$ljk+=$val['goods_number'];
			$total_cake+=$val['goods_number'];
		}
		if($val['bonus']>0&&($val['money_paid']>0||$val['order_amount']>0)&&$val['bonus']<$val['goods_amount'])
		{
			$cuxiao+=$val['goods_number'];
			$total_cake+=$val['goods_number'];
		}
		if($val['surplus']==0&&$val['bonus']==0&&($val['money_paid']>0||$val['order_amount']>0)&&$val['pay_note']!='月结')
		{
			$normal+=$val['goods_number'];
			$total_cake+=$val['goods_number'];
		}
		if($val['pay_note']=='月结')
		{
			$yuejie+=$val['goods_number'];
			$total_cake+=$val['goods_number'];
		}
		if($val['pay_note']=='销售活动'||$val['pay_note']=='销售赠送'||$val['pay_note']=='公司赠送')
		{
			$xshd+=$val['goods_number'];
			$total_cake+=$val['goods_number'];
		}
		if((($val['pay_note']=='市场活动'||$val['pay_note']=='市场赠送')&&$val['goods_attr']!='1/9P')||($val['bonus']>0&&$val['money_paid']==0&&$val['order_amount']==0)||$val['bonus']>=$val['goods_amount'])
		{
			$schd+=$val['goods_number'];
			$total_cake+=$val['goods_number'];
		}
		if($val['goods_attr']=='1/9P')
		{
			$scmini+=$val['goods_number'];
		}
	}
	$res2=mysql_query("SELECT  b.order_sn, a.goods_name,a.goods_attr, a.goods_number,b.surplus,b.goods_amount,b.bonus,b.money_paid,b.order_amount, b.pay_name,b.pay_note,best_time FROM `ecs_order_goods` AS a LEFT JOIN ecs_order_info AS b ON a.order_id = b.order_id WHERE b.order_status=1 
					AND a.goods_price >=45 and best_time like '%".$date2."%' ORDER BY surplus desc,bonus desc,pay_note desc");
	$order_list2=array();
	while($row1=mysql_fetch_assoc($res2))
	{
	$order_list2[]=$row1;
	}
	$ljk2=0;
	$normal2=0;
	$cuxiao2=0;
	$yuejie2=0;
	$xshd2=0;
	$schd2=0;
	$scmini2=0;
	$total_cake2=0;
	if($order_list2)
	{
	foreach($order_list2 as $val)
	{
		if($val['surplus']>0)
		{
			$ljk2+=$val['goods_number'];
			$total_cake2+=$val['goods_number'];
		}
		if($val['bonus']>0&&($val['money_paid']>0||$val['order_amount']>0)&&$val['bonus']<$val['goods_amount'])
		{
			$cuxiao2+=$val['goods_number'];
			$total_cake2+=$val['goods_number'];
		}
		if($val['surplus']==0&&$val['bonus']==0&&($val['money_paid']>0||$val['order_amount']>0)&&$val['pay_note']!='月结')
		{
			$normal2+=$val['goods_number'];
			$total_cake2+=$val['goods_number'];
		}
		if($val['pay_note']=='月结')
		{
			$yuejie2+=$val['goods_number'];
			$total_cake2+=$val['goods_number'];
		}
		if($val['pay_note']=='销售活动'||$val['pay_note']=='销售赠送'||$val['pay_note']=='公司赠送')
		{
			$xshd2+=$val['goods_number'];
			$total_cake2+=$val['goods_number'];
		}
		if((($val['pay_note']=='市场活动'||$val['pay_note']=='市场赠送')&&$val['goods_attr']!='1/9P')||($val['bonus']>0&&$val['money_paid']==0&&$val['order_amount']==0)||$val['bonus']>=$val['goods_amount'])
		{
			$schd2+=$val['goods_number'];
			$total_cake2+=$val['goods_number'];
		}
		if($val['goods_attr']=='1/9P')
		{
			$scmini2+=$val['goods_number'];
		}
	}
	}
	function sendsms($mobile,$content)
	{
	$cont=urlencode($content);
	file_get_contents('http://sdk.kuai-xin.com:8888/sms.aspx?action=send&userid=4333&account=s120018&password=wangjianming123&mobile='.$mobile.'&content='.$cont.'&sendTime=');
	}
	$content="姚总:今日蛋糕共".$total_cake."个,";
	if($total_cake)
	{
		$content.="其中";
		if($ljk)
		{
			$content.="礼金卡".$ljk.",";
		}
		if($cuxiao)
		{
			$content.="促销".$cuxiao.",";
		}
		if($normal)
		{
			$content.="正常".$normal.",";
		}
		if($yuejie)
		{
			$content.="月结".$yuejie.",";
		}
		if($schd)
		{
			$content.="市场".$schd.",";
		}
		if($xshd)
		{
			$content.="销售".$xshd.",";
		}
		if($scmini)
		{
			$content.="mini:".$scmini.",";
		}
	}
	$content.="明日共".$total_cake2."个,";
	if($total_cake2)
	{
		$content.="其中";
		if($ljk2)
		{
			$content.="礼金卡".$ljk2.",";
		}
		if($cuxiao2)
		{
			$content.="促销".$cuxiao2.",";
		}
		if($normal2)
		{
			$content.="正常".$normal2.",";
		}
		if($yuejie2)
		{
			$content.="月结".$yuejie2.",";
		}
		if($schd2)
		{
			$content.="市场".$schd2.",";
		}
		if($xshd2)
		{
			$content.="销售".$xshd2.",";
		}
		if($scmini2)
		{
			$content.="mini:".$scmini2;
		}
	}
	
	$mobile='15842790458';
	$mobile1='13811000692';
	$mobile2='13240783631';
	//$mobile3='18600092121';
	sendsms($mobile,$content);
	sendsms($mobile1,$content);
	sendsms($mobile2,$content);
	//sendsms($mobile3,$content);
	echo "发送短信成功！";
