<?php
$data = array (
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '芝士',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '5',
    'name' => '芝士',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 10,
    'level' => 0,
    'id' => '2',
    'name' => '巧克力',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '附件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 0,
    'id' => '6',
    'name' => '附件',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '慕斯',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 8,
    'level' => 0,
    'id' => '3',
    'name' => '慕斯',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '电子类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '7',
    'name' => '电子类',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '水果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 5,
    'level' => 0,
    'id' => '4',
    'name' => '水果',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '奶油',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 17,
    'level' => 0,
    'id' => '1',
    'name' => '奶油',
  ),
);
?>